add_rules("mode.debug", "mode.release")

set_warnings("all", "error")
set_languages("c++20")
add_cxflags("-Wno-maybe-uninitialized")

package("scope_guard")
	add_urls("https://github.com/Neargye/scope_guard.git")
	add_versions("0.9.1", "8444f7096ea4874817d3421dc8ca596e984d6eaf")
	add_deps("cmake")
	on_install(function(package)
        import("package.tools.cmake").install(package)
    end)
package_end()

add_requires("fmt 9.1.0")
add_requires("spdlog 1.10.0", { configs = { fmt_external = true } })
add_requires("boost 1.78.0")
add_requires("scope_guard 0.9.1")

target("miniss")
    set_kind("static")
    add_includedirs("include", { public = true })
    add_files("src/**.cpp")
    add_packages("fmt", { public = true })
    add_packages("spdlog", { public = true })
    add_packages("boost", { public = true })
    add_packages("scope_guard", { public = true })

includes("test/")
